services:
  backend:
    build:
      context: . #maintain context (or file system) only in the webservce folder. (i think lets keep it root since we need access to pyporject etc)
      #so for this build process and this docker file the file system begins in the webservice folder.
      dockerfile: webservice/backend.dockerfile
    container_name: gophergpt-webservice
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./webservice/data:/app/data
    depends_on:        # wait for postgres container
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    container_name: gophergpt-frontend
    ports:
      - "3000:3000"
    depends_on: #link both services, and change in react app to access instead of local host to backend, 
    #compose and docker do all the dns stuff for us.
      - backend
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    container_name: gophergpt-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gophergpt
      POSTGRES_PASSWORD: gophergpt
      POSTGRES_DB: gophergpt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: gophergpt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always


volumes:
  postgres_data:
  redis_data:
